name: CI

on: [push, pull_request]

jobs:

  test-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      # Fail build if there are warnings
      # build with TLS just for compilation coverage
      run: make REDIS_CFLAGS='-Werror' BUILD_TLS=yes
    - name: test
      run: |
        sudo apt-get install tcl8.6 tclx
        ./runtest --verbose --tags -slow --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose --dump-logs

  test-sanitizer-address:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make SANITIZER=address REDIS_CFLAGS='-Werror'
      - name: testprep
        run: sudo apt-get install tcl8.6 tclx -y
      - name: test
        run: ./runtest --verbose --tags -slow --dump-logs
      - name: module api test
        run: ./runtest-moduleapi --verbose --dump-logs

  build-debian-old:
    runs-on: ubuntu-latest
    container: debian:oldoldstable
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        apt-get update && apt-get install -y build-essential
        make REDIS_CFLAGS='-Werror'
  build-macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make REDIS_CFLAGS='-Werror'

  build-32bit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        sudo apt-get update && sudo apt-get install libc6-dev-i386
        make REDIS_CFLAGS='-Werror' 32bit
  build-libc-malloc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make REDIS_CFLAGS='-Werror' MALLOC=libc

  build-centos7-jemalloc:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        yum -y install gcc make
        make REDIS_CFLAGS='-Werror'
  test-ubuntu-jemalloc:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make REDIS_CFLAGS='-Werror -DREDIS_TEST'
    - name: testprep
      run: sudo apt-get install tcl8.6 tclx
    - name: test
      run: ./runtest --accurate --verbose --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel
    - name: cluster tests
      run: ./runtest-cluster
    - name: unittest
      run: ./src/redis-server test all
      
  test-ubuntu-libc-malloc:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make MALLOC=libc
    - name: testprep
      run: sudo apt-get install tcl8.6 tclx
    - name: test
      run: ./runtest --accurate --verbose --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel
    - name: cluster tests
      run: ./runtest-cluster
      
  test-ubuntu-no-malloc-usable-size:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make MALLOC=libc CFLAGS=-DNO_MALLOC_USABLE_SIZE
    - name: testprep
      run: sudo apt-get install tcl8.6 tclx
    - name: test
      run: ./runtest --accurate --verbose --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel
    - name: cluster tests
      run: ./runtest-cluster
      
  test-ubuntu-32bit:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        sudo apt-get update && sudo apt-get install libc6-dev-i386
        make 32bit REDIS_CFLAGS='-Werror -DREDIS_TEST'
    - name: testprep
      run: sudo apt-get install tcl8.6 tclx
    - name: test
      run: ./runtest --accurate --verbose --dump-logs
    - name: module api test
      run: |
        make -C tests/modules 32bit
        ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel
    - name: cluster tests
      run: ./runtest-cluster
    - name: unittest
      run: ./src/redis-server test all   
      
  test-ubuntu-tls:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        make BUILD_TLS=yes
    - name: testprep
      run: |
        sudo apt-get install tcl8.6 tclx tcl-tls
        ./utils/gen-test-certs.sh
    - name: test
      run: |
        ./runtest --accurate --verbose --tls --dump-logs 
        ./runtest --accurate --verbose --dump-logs 
    - name: module api test
      run: |
        ./runtest-moduleapi --verbose --tls 
        ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: |
        ./runtest-sentinel --tls 
        ./runtest-sentinel 
    - name: cluster tests
      run: |
        ./runtest-cluster --tls 
        ./runtest-cluster
        
  test-ubuntu-io-threads:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        make
    - name: testprep
      run: sudo apt-get install tcl8.6 tclx
    - name: test
      run: ./runtest --config io-threads 4 --config io-threads-do-reads yes --accurate --verbose --tags network --dump-logs
    - name: cluster tests
      run: ./runtest-cluster --config io-threads 4 --config io-threads-do-reads yes
      
  test-valgrind:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make valgrind REDIS_CFLAGS='-Werror -DREDIS_TEST'
    - name: testprep
      run: |
        sudo apt-get update
        sudo apt-get install tcl8.6 tclx valgrind -y
    - name: test
      run: ./runtest --valgrind --verbose --clients 1 --tags -large-memory --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --valgrind --no-latency --verbose --clients 1
    - name: unittest
      run: |
        valgrind --track-origins=yes --suppressions=./src/valgrind.sup --show-reachable=no --show-possibly-lost=no --leak-check=full --log-file=err.txt ./src/redis-server test all
        if grep -q 0x err.txt; then cat err.txt; exit 1; fi  
        
  test-valgrind-no-malloc-usable-size:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make valgrind CFLAGS="-DNO_MALLOC_USABLE_SIZE"
    - name: testprep
      run: |
        sudo apt-get update
        sudo apt-get install tcl8.6 tclx valgrind -y
    - name: test
      run: ./runtest --valgrind --verbose --clients 1 --tags -large-memory --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --valgrind --no-latency --verbose --clients 1
   
  test-centos7-jemalloc:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    container: centos:7
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        yum -y install gcc make
        make
    - name: testprep
      run: yum -y install which tcl tclx
    - name: test
      run: ./runtest --accurate --verbose --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel
    - name: cluster tests
      run: ./runtest-cluster
  
  test-centos7-tls:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    container: centos:7
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        yum -y install centos-release-scl epel-release
        yum -y install devtoolset-7 openssl-devel openssl
        scl enable devtoolset-7 "make BUILD_TLS=yes"
    - name: testprep
      run: |
        yum -y install tcl tcltls tclx
        ./utils/gen-test-certs.sh
    - name: test
      run: |
        ./runtest --accurate --verbose --tls --dump-logs
        ./runtest --accurate --verbose --dump-logs
    - name: module api test
      run: |
        ./runtest-moduleapi --verbose --tls 
        ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: |
        ./runtest-sentinel --tls 
        ./runtest-sentinel
    - name: cluster tests
      run: |
        ./runtest-cluster --tls 
        ./runtest-cluster
  test-macos-latest:
    runs-on: macos-latest
    if: github.repository == 'hwware/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run: ./runtest --accurate --verbose --no-latency --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel
    - name: cluster tests
      run: ./runtest-cluster

  test-freebsd:
    runs-on: macos-latest
    if: github.repository == 'hwware/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: test
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        sync: rsync
        prepare: pkg install -y bash gmake lang/tcl86 lang/tclx
        run: >
          gmake || exit 1 ;
          if true ; then ./runtest --accurate --verbose --no-latency --tags -large-memory --dump-logs || exit 1 ; fi ;
          if true ; then MAKE=gmake ./runtest-moduleapi --verbose  || exit 1 ; fi ;
          if true ; then ./runtest-sentinel  || exit 1 ; fi ;
          if true ; then ./runtest-cluster || exit 1 ; fi ;
  test-alpine-jemalloc:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    container: alpine:latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
          apk add build-base
          make REDIS_CFLAGS='-Werror'
    - name: testprep
      run: apk add tcl procps tclx
    - name: test
      run: ./runtest --accurate --verbose --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel
    - name: cluster tests
      run: ./runtest-cluster

  test-alpine-libc-malloc:
    runs-on: ubuntu-latest
    if: github.repository == 'hwware/redis'
    container: alpine:latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
          apk add build-base
          make REDIS_CFLAGS='-Werror' USE_JEMALLOC=no CFLAGS=-DUSE_MALLOC_USABLE_SIZE
    - name: testprep
      run: apk add tcl procps tclx
    - name: test
      run: ./runtest --accurate --verbose --dump-logs 
    - name: module api test
      run: ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel 
    - name: cluster tests
      run: ./runtest-cluster