name: Daily

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:

  test-ubuntu-jemalloc:
    runs-on: ubuntu-latest
    if: github.repository == 'redis/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run: |
        sudo apt-get install tcl8.5
        ./runtest --accurate --verbose --single unit/tracking
    - name: module api test
      run: ./runtest-moduleapi --verbose --single unit/tracking
    - name: sentinel tests
      run: ./runtest-sentinel --single unit/tracking
    - name: cluster tests
      run: ./runtest-cluster --single unit/tracking

  test-ubuntu-libc-malloc:
    runs-on: ubuntu-latest
    if: github.repository == 'redis/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make MALLOC=libc
    - name: test
      run: |
        sudo apt-get install tcl8.5
        ./runtest --accurate --verbose --single unit/tracking
    - name: module api test
      run: ./runtest-moduleapi --verbose --single unit/tracking
    - name: sentinel tests
      run: ./runtest-sentinel --single unit/tracking
    - name: cluster tests
      run: ./runtest-cluster --single unit/tracking

  test-ubuntu-32bit:
    runs-on: ubuntu-latest
    if: github.repository == 'redis/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        sudo apt-get update && sudo apt-get install libc6-dev-i386
        make 32bit
    - name: test
      run: |
        sudo apt-get install tcl8.5
        ./runtest --accurate --verbose --single unit/tracking
    - name: module api test
      run: |
        make -C tests/modules 32bit # the script below doesn't have an argument, we must build manually ahead of time
        ./runtest-moduleapi --verbose --single unit/tracking
    - name: sentinel tests
      run: ./runtest-sentinel --single unit/tracking
    - name: cluster tests
      run: ./runtest-cluster --single unit/tracking

  test-ubuntu-tls:
    runs-on: ubuntu-latest
    if: github.repository == 'redis/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        make BUILD_TLS=yes
    - name: test
      run: |
        sudo apt-get install tcl8.5 tcl-tls
        ./utils/gen-test-certs.sh
        ./runtest --accurate --verbose --tls --single unit/tracking
        ./runtest --accurate --verbose --single unit/tracking
    - name: module api test
      run: |
        ./runtest-moduleapi --verbose --tls --single unit/tracking
        ./runtest-moduleapi --verbose --single unit/tracking
    - name: sentinel tests
      run: |
        ./runtest-sentinel --tls --single unit/tracking
        ./runtest-sentinel --single unit/tracking
    - name: cluster tests
      run: |
        ./runtest-cluster --tls --single unit/tracking
        ./runtest-cluster --single unit/tracking

  test-valgrind:
    runs-on: ubuntu-latest
    if: github.repository == 'redis/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make valgrind
    - name: test
      run: |
        sudo apt-get update
        sudo apt-get install tcl8.5 valgrind -y
        ./runtest --valgrind --verbose --clients 1 --single unit/tracking
    - name: module api test
      run: ./runtest-moduleapi --valgrind --verbose --clients 1 --single unit/tracking

  test-centos7-jemalloc:
    runs-on: ubuntu-latest
    if: github.repository == 'redis/redis'
    container: centos:7
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        yum -y install gcc make
        make
    - name: test
      run: |
        yum -y install which tcl
        ./runtest --accurate --verbose --single unit/tracking
    - name: module api test
      run: ./runtest-moduleapi --verbose --single unit/tracking
    - name: sentinel tests
      run: ./runtest-sentinel --single unit/tracking
    - name: cluster tests
      run: ./runtest-cluster --single unit/tracking

  test-centos6-jemalloc:
    runs-on: ubuntu-latest
    if: github.repository == 'redis/redis'
    container: centos:6
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: |
        yum -y install gcc make
        make
    - name: test
      run: |
        yum -y install which tcl util-linux-ng
        ./runtest --accurate --verbose --single unit/tracking
    - name: module api test
      run: ./runtest-moduleapi --verbose --single unit/tracking
    - name: sentinel tests
      run: ./runtest-sentinel --single unit/tracking
    - name: cluster tests
      run: ./runtest-cluster --single unit/tracking

  test-centos7-tls:
    runs-on: ubuntu-latest
    if: github.repository == 'redis/redis'
    container: centos:7
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        yum -y install centos-release-scl epel-release
        yum -y install devtoolset-7 openssl-devel openssl
        scl enable devtoolset-7 "make BUILD_TLS=yes"
    - name: test
      run: |
        yum -y install tcl tcltls
        ./utils/gen-test-certs.sh
        ./runtest --accurate --verbose --tls --single unit/tracking
        ./runtest --accurate --verbose --single unit/tracking
    - name: module api test
      run: |
        ./runtest-moduleapi --verbose --tls --single unit/tracking
        ./runtest-moduleapi --verbose --single unit/tracking
    - name: sentinel tests
      run: |
        ./runtest-sentinel --tls --single unit/tracking
        ./runtest-sentinel --single unit/tracking
    - name: cluster tests
      run: |
        ./runtest-cluster --tls --single unit/tracking
        ./runtest-cluster --single unit/tracking

  test-macos-latest:
    runs-on: macos-latest
    if: github.repository == 'redis/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run: |
        ./runtest --accurate --verbose --no-latency --single unit/tracking
    - name: module api test
      run: ./runtest-moduleapi --verbose --single unit/tracking
    - name: sentinel tests
      run: ./runtest-sentinel --single unit/tracking
    - name: cluster tests
      run: ./runtest-cluster --single unit/tracking

